# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate pairwise distance between points
#'
#' @param x numeric matrix with dimensions in the columns and stimuli in the rows
#' @param r Minkowski metric (1 = city block, 2 = euclidean)
#'
NULL

pair_dist_cpp <- function(x, r) {
    .Call('_MDShelper_pair_dist_cpp', PACKAGE = 'MDShelper', x, r)
}

